import {expect,test} from 'bun:test';
import {watchResearchRuntime,validateResearchWatchLease,type ResearchWatchLease,type ResearchWatchObservation} from '../src/research-runtime-watch';
const lease:ResearchWatchLease={jobId:'abc12345',sessionId:'abc12345-0000-4000-8000-000000000000',worktree:'C:/campaign/work',startedAt:'2026-09-05T00:00:00Z',deadlineAt:'2026-09-05T00:01:00Z',tokenCap:100,tokenMetric:'daemon-reported',pollMs:100,telemetryGraceMs:300};
const observation=(changes:Partial<ResearchWatchObservation>={}):ResearchWatchObservation=>({jobId:lease.jobId,sessionId:lease.sessionId,worktree:lease.worktree,createdAt:lease.startedAt,state:'working',observedTokens:1,...changes});
function harness(values:Array<ResearchWatchObservation|null>,stopWorks=true,start=Date.parse(lease.startedAt)) {
 let now=start,index=0,stopped=false;const stops:string[]=[],events:any[]=[];
 return {stops,events,port:{now:()=>now,monotonicNow:()=>now,observe:async()=>stopped?observation({state:'stopped',observedTokens:100}):values[Math.min(index++,values.length-1)],stop:async(id:string)=>{stops.push(id);stopped=stopWorks;},wait:async(ms:number)=>{now+=ms;},record:async(e:any)=>{events.push(e);}}};
}
test('threshold stops exact identity and confirms terminal state without restarting',async()=>{const h=harness([observation({observedTokens:80}),observation({observedTokens:105})]);expect(await watchResearchRuntime(lease,h.port)).toMatchObject({status:'stopped',reason:'token-threshold',stopAttempts:1,observedTokens:105});expect(h.stops).toEqual([lease.jobId]);});
test('deadline works independently of missing token telemetry',async()=>{const h=harness([observation({observedTokens:null})],true,Date.parse(lease.deadlineAt));expect(await watchResearchRuntime(lease,h.port)).toMatchObject({status:'stopped',reason:'deadline'});});
test('a transient missing observation rechecks the same job; sustained missing ownership never stops another job',async()=>{let h=harness([null,observation({state:'done'})]);expect((await watchResearchRuntime(lease,h.port)).status).toBe('terminal');expect(h.stops).toEqual([]);h=harness([null]);expect((await watchResearchRuntime(lease,h.port)).reason).toBe('telemetry-unavailable');expect(h.stops).toEqual([]);});
test('mismatched session/worktree/creation identity is never stopped',async()=>{for(const change of [{sessionId:'abc12345-1111-4000-8000-000000000000'},{worktree:'C:/unrelated'},{createdAt:'2026-09-04T00:00:00Z'}]){const h=harness([observation(change)]);expect((await watchResearchRuntime(lease,h.port)).reason).toBe('identity-mismatch');expect(h.stops).toEqual([]);}});
test('confirmed ownership with missing usage or regressed counter fails closed',async()=>{for(const values of [[observation({observedTokens:null})],[observation({observedTokens:60}),observation({observedTokens:50})]]){const h=harness(values);expect((await watchResearchRuntime(lease,h.port)).status).toBe('stopped');expect(h.stops).toHaveLength(1);}});
test('unsuccessful stop is bounded and remains unconfirmed',async()=>{const h=harness([observation({observedTokens:101})],false);expect(await watchResearchRuntime(lease,h.port)).toMatchObject({status:'attention',reason:'stop-unconfirmed:token-threshold',stopAttempts:2});});
test('invalid budgets/identities are rejected before monitoring',()=>{for(const change of [{tokenCap:NaN},{tokenCap:-1},{jobId:'all'},{worktree:'relative'},{pollMs:0}])expect(()=>validateResearchWatchLease({...lease,...change})).toThrow();});

test('wall-clock rollback cannot extend the deadline',async()=>{const h=harness([observation()]);let wall=Date.parse(lease.startedAt);h.port.now=()=>wall;const wait=h.port.wait;h.port.wait=async ms=>{wall-=ms;await wait(ms);};expect(await watchResearchRuntime(lease,h.port)).toMatchObject({status:'stopped',reason:'deadline',stopAttempts:1});});

test('natural completion after a stop request is not reported as confirmed cancellation',async()=>{const h=harness([observation({observedTokens:101}),observation({state:'done',observedTokens:101})],false);expect(await watchResearchRuntime(lease,h.port)).toMatchObject({status:'terminal',stopAttempts:1});});

test('malformed observation fails ownership checks without throwing or stopping',async()=>{const h=harness([observation({worktree:undefined as any})]);expect(await watchResearchRuntime(lease,h.port)).toMatchObject({status:'attention',reason:'identity-mismatch'});expect(h.stops).toEqual([]);});
