export type InterpretationState = "ACTIVE" | "OPEN" | "SUPPORTED" | "PROPOSED" | "UNMEASURED" | "BLOCKED" | "CONTEXT";

export type InterpretationNode = {
  id: string;
  kind: "objective" | "quest" | "decision" | "track" | "claim" | "proposal" | "concept";
  kicker: string;
  title: string;
  summary: string;
  state: InterpretationState;
  trackId?: string;
  why?: string;
  relation?: string;
  evidence?: string[];
  scope?: string[];
  unlocks?: string[];
  metrics?: string[];
  color?: string;
};

export type CampaignInterpretation = {
  source: "frozen-synthesis" | "checked-plan" | "campaign-state";
  objective: InterpretationNode;
  quest: InterpretationNode;
  decision: InterpretationNode;
  progress: string[];
  watchouts: string[];
  tracks: InterpretationNode[];
  claims: InterpretationNode[];
  proposals: InterpretationNode[];
  concepts: InterpretationNode[];
};

const concepts: Array<{ id: string; pattern: RegExp; title: string; summary: string; relation: string; scope: string }> = [
  {
    id: "geometric-23-4",
    pattern: /23[_ ]?4|23\\_4|geometric \(?23/i,
    title: "Geometric (23₄) configuration",
    summary: "A symmetric incidence structure with 23 points and 23 lines, four incidences at every point and on every line, realized by straight lines over the real projective plane.",
    relation: "This is the campaign's north-star existence question. Candidate classifications and algebraic obstructions matter only through how they narrow or supply possible realizations.",
    scope: "Combinatorial incidence, orientability, or symmetry evidence alone does not establish a real straight-line realization.",
  },
  {
    id: "orientation",
    pattern: /orient(?:ation|ability|ed)|oriented matroid/i,
    title: "Orientation and oriented matroids",
    summary: "Sign data encoding which triples lie on which side of one another, providing a combinatorial shadow of a geometric arrangement.",
    relation: "Orientation filters remove candidates that cannot support the required signed incidence behavior before expensive geometry is attempted.",
    scope: "An orientation can be necessary without being stretchable or realizable by actual straight lines.",
  },
  {
    id: "automorphism",
    pattern: /automorphism|asymmetric|trivial[- ]automorphism/i,
    title: "Automorphism group",
    summary: "The incidence-preserving relabelings of a candidate. A trivial automorphism group means no nonidentity relabeling preserves the structure.",
    relation: "Asymmetric candidates diversify the laboratory and reduce the chance that a measurement is merely an artifact of a shared symmetry family.",
    scope: "Low symmetry is a diversity filter, not evidence that a candidate is geometrically realizable.",
  },
  {
    id: "slack",
    pattern: /reduced[- ]slack|slack model|RSEVC/i,
    title: "Reduced slack model",
    summary: "A coordinate-like algebraic encoding with scaling redundancies removed, used here to estimate how many genuinely interacting variables a candidate presents.",
    relation: "A recurring small nonlinear interface could point toward a reusable realization or obstruction method.",
    scope: "The planned measurements are complexity proxies; they are not realization certificates by themselves.",
  },
  {
    id: "liftability",
    pattern: /liftability|deletion[- ]width|LDW/i,
    title: "Liftability deletion width",
    summary: "A bounded proxy for how much of a candidate must be removed before its remaining constraints become easier to lift or reconstruct.",
    relation: "It tests whether apparently complicated candidates share a small hard core that a later exact method could target.",
    scope: "This quantity was not measured in the current run because the sample-size gate failed.",
  },
  {
    id: "v4",
    pattern: /\bV4\b|Klein four/i,
    title: "V₄ symmetry",
    summary: "The Klein four-group symmetry, generated by two commuting involutions, used to quotient a large configuration problem into smaller exact templates.",
    relation: "V₄ lanes trade global generality for sharply structured finite subproblems that can sometimes be certified exactly.",
    scope: "Closing a V₄ template does not settle candidates outside that symmetry class.",
  },
  {
    id: "c2",
    pattern: /\bC2\b|involution/i,
    title: "C₂ symmetry",
    summary: "A two-element cyclic symmetry generated by one involution, providing another way to organize and canonicalize candidate families.",
    relation: "The current C₂ proposal is a correctness forensic: it asks where one expected canonical state disappeared before trusting a larger census.",
    scope: "Repairing bookkeeping changes confidence in the search, not the geometric existence status directly.",
  },
  {
    id: "proof-object",
    pattern: /proof[- ]object|certificate|independent checker/i,
    title: "Proof object",
    summary: "A portable artifact—such as an exact identity, exhaustive ledger, or certificate—that a small independent checker can verify without trusting the producer.",
    relation: "Proof objects let the campaign convert expensive computation into durable, replayable mathematical evidence.",
    scope: "A producer transcript is reconnaissance until its exact object and assumptions are independently checked.",
  },
];

function text(value: unknown, fallback = ""): string {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

function list(value: unknown): any[] {
  return Array.isArray(value) ? value : [];
}

function claimState(status: unknown): InterpretationState {
  const value = text(status).toUpperCase();
  if (value.includes("NOT_SUPPORTED") || value.includes("BLOCK") || value.includes("REFUT")) return "BLOCKED";
  if (value.includes("UNMEASURED") || value.includes("UNCHANGED") || value.includes("OPEN")) return "UNMEASURED";
  if (value.includes("SUPPORTED") || value.includes("ADVANCED")) return "SUPPORTED";
  if (value.includes("PENDING") || value.includes("PROPOSED")) return "PROPOSED";
  return "CONTEXT";
}

function currentTrack(project: any): string {
  const activeRun = list(project?.researchRuns)
    .filter((run) => ["launching", "running", "blocked", "evidence_ready", "returned_to_sol"].includes(run?.status))
    .sort((left, right) => text(right?.updatedAt).localeCompare(text(left?.updatedAt)))[0];
  return text(activeRun?.strategy?.trackId, text(project?.researchPlan?.response?.lanes?.[0]?.strategy?.trackId));
}

function claimTrack(claim: any, fallback: string): string {
  const value = `${text(claim?.claimId)} ${text(claim?.summary)}`.toUpperCase();
  if (value.includes("ASYM") || value.includes("SUPPLY") || value.includes("CANDIDATE")) return "supply";
  if (value.includes("GEOMETRIC") || value.includes("REALIZATION") || value.includes("DECISION")) return "decision";
  if (value.includes("COVERAGE") || value.includes("CENSUS") || value.includes("V4") || value.includes("C2")) return "coverage";
  return fallback;
}

export function buildCampaignInterpretation(project: any): CampaignInterpretation {
  const synthesis = project?.wave?.synthesis?.response || null;
  const plan = project?.researchPlan?.response || null;
  const brief = synthesis?.operatorBrief || {};
  const charter = project?.strategy?.charter || {};
  const planIsCurrent = Boolean(plan && ["RESEARCH_REVIEW", "RESEARCH_READY", "REVISING"].includes(text(project?.phase)));
  const source: CampaignInterpretation["source"] = planIsCurrent ? "checked-plan" : synthesis ? "frozen-synthesis" : plan ? "checked-plan" : "campaign-state";
  const activeTrackId = currentTrack(project);

  const objective: InterpretationNode = {
    id: "campaign-objective",
    kind: "objective",
    kicker: "NORTH STAR",
    title: text(charter.question, text(project?.role, "Campaign objective")),
    summary: text(charter.thesis, "Advance the campaign's central mathematical question through bounded, independently checkable evidence."),
    state: "OPEN",
    why: "Every lane should change a denominator, candidate supply, candidate decision, or the confidence in a reusable method.",
    relation: "This objective owns the strategic tracks and provides the test for whether activity is genuine progress.",
    scope: ["The objective remains open until promotion-grade evidence changes its mathematical status."],
  };

  const quest: InterpretationNode = {
    id: "current-quest",
    kind: "quest",
    kicker: "CURRENT QUEST",
    title: planIsCurrent ? text(plan?.summary, "Shape the next bounded wave from the synthesized result.") : text(brief.headline, text(plan?.summary, `Campaign phase: ${text(project?.phase, "planning").replaceAll("_", " ")}`)),
    summary: planIsCurrent ? text(plan?.operatorGuidance, "The synthesis is being translated into checked, resource-bounded launch contracts.") : text(brief.whereWeAre, text(plan?.operatorGuidance, text(project?.wave?.aggregate?.nextBoundary, objective.summary))),
    state: planIsCurrent ? "ACTIVE" : project?.phase === "DECISION_REQUIRED" ? "SUPPORTED" : "ACTIVE",
    trackId: activeTrackId,
    why: planIsCurrent ? "This is the current planning problem: decide which proposed branch best converts the last result into the next defensible knowledge gain." : text(brief.currentFocus, "This is the narrowest currently authorized move that can improve the campaign's knowledge state."),
    relation: `This quest advances the ${activeTrackId || "current"} track while remaining subordinate to the campaign objective.`,
    evidence: list(brief.recentProgress).map((item) => text(item)).filter(Boolean),
    scope: list(brief.watchouts).map((item) => text(item)).filter(Boolean),
  };

  const proposedLanes = (planIsCurrent && list(plan?.lanes).length ? list(plan.lanes).filter((lane) => text(lane?.action).toUpperCase() !== "DROP") : list(synthesis?.nextWave?.lanes).length ? list(synthesis.nextWave.lanes) : list(plan?.lanes))
    .filter(Boolean);
  const activeTrackIds = new Set(planIsCurrent
    ? proposedLanes.map((lane) => text(lane?.strategy?.trackId, text(lane?.trackId))).filter(Boolean)
    : [activeTrackId].filter(Boolean));
  const decision: InterpretationNode = {
    id: "next-decision",
    kind: "decision",
    kicker: "HUMAN DECISION",
    title: planIsCurrent ? "Approve, revise, or block the checked next-wave plan." : text(brief.nextDecision, text(plan?.operatorGuidance, "Choose the next bounded campaign move.")),
    summary: planIsCurrent ? text(plan?.operatorGuidance, text(plan?.summary)) : text(synthesis?.nextWave?.objective, text(plan?.summary, "Select only work whose expected knowledge delta justifies its resource and evidence contract.")),
    state: project?.controlState?.recovery?.required ? "BLOCKED" : "PROPOSED",
    why: "The campaign branches here; no proposal acquires authority until the operator chooses and a checked schedule is frozen.",
    relation: "The selected branch returns to the main campaign line through planning, evidence intake, synthesis, and another explicit decision.",
    unlocks: proposedLanes.map((lane) => text(lane?.objective, text(lane?.question, text(lane?.taskId)))).filter(Boolean),
  };

  const tracks: InterpretationNode[] = list(charter.tracks).map((track) => ({
    id: `track-${text(track?.id, "unknown")}`,
    kind: "track",
    kicker: `${Math.round(Number(track?.targetShare || 0) * 100)}% TARGET`,
    title: text(track?.label, text(track?.id, "Research track")),
    summary: text(track?.purpose, "A persistent route from bounded work back to the campaign objective."),
    state: activeTrackIds.has(text(track?.id)) ? "ACTIVE" : "OPEN",
    trackId: text(track?.id),
    relation: `This track is one of ${Math.max(1, list(charter.tracks).length)} balanced routes to the campaign objective.`,
    metrics: list(track?.metrics).map((item) => text(item)).filter(Boolean),
    color: text(track?.color, "#71d6a0"),
  }));

  const claims: InterpretationNode[] = list(synthesis?.claimDeltas).map((claim, index) => ({
    id: `claim-${text(claim?.claimId, String(index)).replace(/[^a-z0-9-]+/gi, "-").toLowerCase()}`,
    kind: "claim",
    kicker: "KNOWLEDGE DELTA",
    title: text(claim?.summary, text(claim?.claimId, "Claim update")),
    summary: text(claim?.summary, "The synthesis recorded a bounded change in campaign knowledge."),
    state: claimState(claim?.proposedStatus),
    trackId: claimTrack(claim, activeTrackId),
    why: `Status: ${text(claim?.proposedStatus, "context only").replaceAll("_", " ")}.`,
    relation: "Claim deltas are the bridge between a completed lane and measurable progress toward the campaign objective.",
    evidence: list(claim?.evidence).map((item) => text(item)).filter(Boolean),
    scope: list(claim?.objections).map((item) => text(item)).filter(Boolean),
  }));

  const proposals: InterpretationNode[] = proposedLanes.map((lane, index) => {
    const planLane = list(plan?.lanes).find((candidate) => candidate?.taskId === lane?.taskId) || lane;
    const trackId = text(planLane?.strategy?.trackId, text(lane?.trackId, "unassigned"));
    return {
      id: `proposal-${text(lane?.taskId, String(index)).replace(/[^a-z0-9-]+/gi, "-").toLowerCase()}`,
      kind: "proposal",
      kicker: `PROPOSED · ${text(planLane?.strategy?.workKind, "research").toUpperCase()}`,
      title: text(lane?.objective, text(planLane?.question, text(lane?.taskId, "Bounded follow-up"))),
      summary: text(planLane?.rationale, text(lane?.objective, "A bounded follow-up proposed by synthesis.")),
      state: "PROPOSED" as const,
      trackId,
      why: text(planLane?.strategy?.expectedDelta, "It is proposed because it can change a named campaign metric."),
      relation: `This branch feeds the ${trackId} track and still requires a checked plan and human-confirmed schedule.`,
      evidence: [text(planLane?.evidenceExpected)].filter(Boolean),
      scope: [text(planLane?.stopCondition)].filter(Boolean),
      unlocks: [text(planLane?.strategy?.expectedDelta)].filter(Boolean),
    };
  });

  const searchable = JSON.stringify({ objective, quest, decision, claims, proposals });
  const matchedConcepts: InterpretationNode[] = concepts.filter((concept) => concept.pattern.test(searchable)).map((concept) => ({
    id: `concept-${concept.id}`,
    kind: "concept",
    kicker: "OBJECT CODEX",
    title: concept.title,
    summary: concept.summary,
    state: "CONTEXT",
    why: concept.relation,
    relation: "This explainer is educational context; use the linked claim and evidence nodes for campaign authority.",
    scope: [concept.scope],
  }));

  return {
    source,
    objective,
    quest,
    decision,
    progress: list(brief.recentProgress).map((item) => text(item)).filter(Boolean),
    watchouts: list(brief.watchouts).map((item) => text(item)).filter(Boolean),
    tracks,
    claims,
    proposals,
    concepts: matchedConcepts,
  };
}

export function interpretationAuthority(state: InterpretationState): string {
  const labels: Record<InterpretationState, string> = {
    ACTIVE: "Current bounded focus; activity is not automatically mathematical progress.",
    OPEN: "Open objective or track; no terminal mathematical conclusion is implied.",
    SUPPORTED: "Supported within the displayed evidence and scope; promotion may still require independent intake.",
    PROPOSED: "Advisory only; this branch has no launch or claim authority.",
    UNMEASURED: "The relevant question or quantity remains unchanged or was not measured.",
    BLOCKED: "The displayed evidence does not support this claim or the transition is presently gated.",
    CONTEXT: "Educational context only; it does not carry campaign authority.",
  };
  return labels[state];
}
